swipe:
  3:
    left:
      command: 'xdotool key XF86AudioPrev'
    right:
      command: 'xdotool key XF86AudioNext'
    up:
      command: 'xdotool key XF86AudioRaiseVolume'
    down:
      command: 'xdotool key XF86AudioLowerVolume'
  4:
    left:
      command: 'xdotool key ctrl+alt+Up'
    right:
      command: 'xdotool key ctrl+alt+Down'

tap:
  3:
    command: 'xdotool key XF86AudioPlay'

threshold:
  swipe: 0.2
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1

plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
